"""empty message

Revision ID: 35bd4584ca4f
Revises: faebbde96546
Create Date: 2018-12-27 18:51:15.229479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35bd4584ca4f'
down_revision = 'faebbde96546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('is_up', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'is_up')
    # ### end Alembic commands ###
