"""empty message

Revision ID: 363f0fb3be81
Revises: 35bd4584ca4f
Create Date: 2018-12-28 14:46:50.351162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '363f0fb3be81'
down_revision = '35bd4584ca4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('article', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'subject', ['subject_id'], ['id'])
    op.drop_column('article', 'subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('subject', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'subject_id')
    op.drop_table('subject')
    # ### end Alembic commands ###
