"""empty message

Revision ID: 759cd1b680d9
Revises: 363f0fb3be81
Create Date: 2018-12-30 15:39:41.395762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '759cd1b680d9'
down_revision = '363f0fb3be81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'likeNumber',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('article', 'unlikeNumber',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'unlikeNumber',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('article', 'likeNumber',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
