"""empty message

Revision ID: ca7d0b8bd994
Revises: 7e9fdb309f5d
Create Date: 2018-12-30 20:03:20.054681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7d0b8bd994'
down_revision = '7e9fdb309f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_ip', sa.Text(), nullable=False),
    sa.Column('is_up', sa.Boolean(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_comment')
    # ### end Alembic commands ###
