"""empty message

Revision ID: faebbde96546
Revises: 23926b2db0ad
Create Date: 2018-12-26 18:29:27.909011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faebbde96546'
down_revision = '23926b2db0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_ip', sa.Text(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('article', sa.Column('abstract', sa.String(length=100), nullable=False))
    op.add_column('article', sa.Column('highlight', sa.String(length=100), nullable=False))
    op.add_column('comment', sa.Column('likeNumber', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('unlikeNumber', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('viewCount', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'viewCount')
    op.drop_column('comment', 'unlikeNumber')
    op.drop_column('comment', 'likeNumber')
    op.drop_column('article', 'highlight')
    op.drop_column('article', 'abstract')
    op.drop_table('vote')
    # ### end Alembic commands ###
